# Generated by Django 4.0.6 on 2022-08-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv_shows',
            name='year',
            field=models.IntegerField(),
        ),
    ]
