# Generated by Django 4.0.6 on 2022-09-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv_shows',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tv_shows/'),
        ),
    ]
