# Generated by Django 4.0.6 on 2022-09-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0005_alter_tv_shows_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv_shows',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='show_image/'),
        ),
    ]
