# Generated by Django 4.0.6 on 2022-08-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Review',
            new_name='review',
        ),
    ]
